# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


tx = State.create(name: 'TEXAS')
State.create(name: 'MISSOURI')
State.create(name: 'VERMONT')
State.create(name: 'MINNESOTA')
State.create(name: 'DELAWARE')
State.create(name: 'MICHIGAN')
State.create(name: 'GEORGIA')
State.create(name: 'MAINE')
State.create(name: 'MARYLAND')
State.create(name: 'MASSACHUSETTS')
State.create(name: 'SOUTH DAKOTA')
State.create(name: 'SOUTH CAROLINA')
State.create(name: 'PENNSYLVANIA')
State.create(name: 'VIRGINIA')
State.create(name: 'CONNECTICUT')
State.create(name: 'COLORADO')
State.create(name: 'OREGON')
fl = State.create(name: 'FLORIDA')
State.create(name: 'INDIANA')
State.create(name: 'UTAH')
State.create(name: 'ILLINOIS')
State.create(name: 'OKLAHOMA')
State.create(name: 'CALIFORNIA')
State.create(name: 'IDAHO')
State.create(name: 'OHIO')
State.create(name: 'RHODE ISLAND')
State.create(name: 'IOWA')
State.create(name: 'LOUISIANA')
State.create(name: 'KENTUCKY')
State.create(name: 'NEW YORK')
State.create(name: 'NEVADA')
State.create(name: 'KANSAS')
State.create(name: 'WYOMING')
State.create(name: 'WEST VIRGINIA')
State.create(name: 'HAWAII')
State.create(name: 'NEW MEXICO')
State.create(name: 'TENNESSEE')
State.create(name: 'NEW JERSEY')
State.create(name: 'NEW HAMPSHIRE')
State.create(name: 'NEBRASKA')
State.create(name: 'NORTH DAKOTA')
State.create(name: 'WISCONSIN')
State.create(name: 'ARIZONA')
State.create(name: 'NORTH CAROLINA')
State.create(name: 'WASHINGTON')
State.create(name: 'ARKANSAS')
State.create(name: 'ALABAMA')
State.create(name: 'MONTANA')
State.create(name: 'ALASKA')
State.create(name: 'MISSISSIPPI')

Comment.create(context:"Wow! So many cases!", state_id: fl.id )
Comment.create(context:"Thanks Spring Break....", state_id: fl.id )
Comment.create(context:"YeeeeHawwwwww Open TX back up!", state_id: tx.id )
Comment.create(context:"Gov. said Covid is over!", state_id: tx.id )